version:                                    '3.5'
services:
  nginx:
    build:
      context:                              .
      dockerfile:                           nginx.Dockerfile
    networks:
      - wrg-net
      - lsrv-net
      - aos-net
      - cos-net
      - iis-net
      - mis-net
      - pos-net
      - csrv-net
      - mrg-net
      - morg-net
      - dis-net
      - drg-net
      - tds-net
      - eso-net
      - sis-net
      - ncs-net
      - cdc-net
    ports:
      - '80:80'
    expose:
      - '80'
    container_name:                         atlas-nginx
  db:
    build:
      context:                              .
      dockerfile:                           db.Dockerfile
    command:                                --default-authentication-plugin=mysql_native_password
    restart:                                always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD:                  the
      MYSQL_DATABASE:                       atlas
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - aos-net
      - cos-net
      - dis-net
      - eso-net
    container_name:                         atlas-db
  wrg:
    image:                                  atlas-wrg:latest
    depends_on:
      - "nginx"
      - "kafka"
    ports:
      - '8581:5005'
    environment:
      WAIT_HOSTS:                           nginx:80
      BOOTSTRAP_SERVERS:                    atlas-kafka:9092
    networks:
      - wrg-net
    expose:
      - '8080'
    container_name:                         atlas-wrg
  lsrv:
    image:                                  atlas-lsrv:latest
    depends_on:
      - "nginx"
      - "kafka"
    ports:
      - '8582:5005'
      - '8484:8484'
    networks:
      - lsrv-net
    expose:
      - '8484'
    container_name:                         atlas-lsrv
  aos:
    image:                                  atlas-aos:latest
    depends_on:
      - "nginx"
      - "kafka"
      - "db"
    ports:
      - '8583:5005'
    environment:
      WAIT_HOSTS:                           db:3306, nginx:80
      BOOTSTRAP_SERVERS:                    atlas-kafka:9092
    networks:
      - aos-net
    expose:
      - '8080'
    container_name:                         atlas-aos
  cos:
    image:                                  atlas-cos:latest
    depends_on:
      - "nginx"
      - "kafka"
      - "db"
    ports:
      - '8584:5005'
    environment:
      WAIT_HOSTS:                           db:3306, nginx:80
      BOOTSTRAP_SERVERS:                    atlas-kafka:9092
    networks:
      - cos-net
    expose:
      - '8080'
    container_name:                         atlas-cos
  iis:
    image:                                  atlas-iis:latest
    depends_on:
      - "nginx"
      - "kafka"
    ports:
      - '8585:5005'
    environment:
      WAIT_HOSTS:                           nginx:80
    networks:
      - iis-net
    expose:
      - '8080'
    container_name:                         atlas-iis
  mis:
    image:                                  atlas-mis:latest
    depends_on:
      - "nginx"
      - "kafka"
    ports:
      - '8586:5005'
    environment:
      WAIT_HOSTS:                           nginx:80
    networks:
      - mis-net
    expose:
      - '8080'
    container_name:                         atlas-mis
  pos:
    image:                                  atlas-pos:latest
    depends_on:
      - "nginx"
      - "kafka"
    ports:
      - '8587:5005'
    environment:
      WAIT_HOSTS:                           nginx:80
      BOOTSTRAP_SERVERS:                    atlas-kafka:9092
    networks:
      - pos-net
    expose:
      - '8080'
    container_name:                         atlas-pos
  mrg:
    image:                                  atlas-mrg:latest
    depends_on:
      - "nginx"
      - "kafka"
    ports:
      - '8588:5005'
    environment:
      WAIT_HOSTS:                           nginx:80
      BOOTSTRAP_SERVERS:                    atlas-kafka:9092
    networks:
      - mrg-net
    expose:
      - '8080'
    container_name:                         atlas-mrg
  morg:
    image:                                  atlas-morg:latest
    depends_on:
      - "nginx"
      - "kafka"
    ports:
      - '8589:5005'
    environment:
      WAIT_HOSTS:                           nginx:80
      BOOTSTRAP_SERVERS:                    atlas-kafka:9092
    networks:
      - morg-net
    expose:
      - '8080'
    container_name:                         atlas-morg
  dis:
    image:                                  atlas-dis:latest
    depends_on:
      - "nginx"
      - "db"
    ports:
      - '8590:5005'
    environment:
      WAIT_HOSTS:                           db:3306, nginx:80
    networks:
      - dis-net
    expose:
      - '8080'
    container_name:                         atlas-dis
  drg:
    image:                                  atlas-drg:latest
    depends_on:
      - "nginx"
    ports:
      - '8591:5005'
    environment:
      WAIT_HOSTS:                           nginx:80
      BOOTSTRAP_SERVERS:                    atlas-kafka:9092
    networks:
      - drg-net
    expose:
      - '8080'
    container_name:                         atlas-drg
  tds:
    image:                                  atlas-tds:latest
    depends_on:
      - "nginx"
    ports:
      - '8592:5005'
    environment:
      WAIT_HOSTS:                           nginx:80
    networks:
      - tds-net
    expose:
      - '8080'
    container_name:                         atlas-tds
  eso:
    image:                                  atlas-eso:latest
    depends_on:
      - "nginx"
      - "db"
    ports:
      - '8593:5005'
    environment:
      WAIT_HOSTS:                           db:3306, nginx:80
    networks:
      - eso-net
    expose:
      - '8080'
    container_name:                         atlas-eso
  sis:
    image:                                  atlas-sis:latest
    depends_on:
      - "nginx"
    ports:
      - '8594:5005'
    environment:
      WAIT_HOSTS:                           nginx:80
    networks:
      - sis-net
    expose:
      - '8080'
    container_name:                         atlas-sis
  ncs:
    image:                                  atlas-ncs:latest
    depends_on:
      - "nginx"
    ports:
      - '8595:5005'
    environment:
      WAIT_HOSTS:                           nginx:80
      BOOTSTRAP_SERVERS:                    atlas-kafka:9092
    networks:
      - ncs-net
    expose:
      - '8080'
    container_name:                         atlas-ncs
  cdc:
    image:                                  atlas-cdc:latest
    depends_on:
      - "nginx"
    ports:
      - '8596:5005'
    environment:
      WAIT_HOSTS:                           nginx:80
      BOOTSTRAP_SERVERS:                    atlas-kafka:9092
    networks:
      - cdc-net
    expose:
      - '8080'
    container_name:                         atlas-cdc
  csrv-0-1:
    image:                                  atlas-csrv:latest
    depends_on:
      - "kafka"
    ports:
      - '8501:5005'
      - '7575:7575'
    environment:
      WAIT_HOSTS:                           nginx:80
      WORLD_ID:                             0
      CHANNEL_ID:                           1
      CHANNEL_PORT:                         7575
      HOST_ADDRESS:                         192.168.56.2
      BOOTSTRAP_SERVERS:                    atlas-kafka:9092
    networks:
      - csrv-net
    expose:
      - '7575'
    container_name:                         atlas-csrv-0-1
  csrv-0-2:
    image:                                  atlas-csrv:latest
    depends_on:
      - "kafka"
    ports:
      - '8502:5005'
      - '7576:7576'
    environment:
      WAIT_HOSTS:                           nginx:80
      WORLD_ID:                             0
      CHANNEL_ID:                           2
      CHANNEL_PORT:                         7576
      HOST_ADDRESS:                         192.168.56.2
      BOOTSTRAP_SERVERS:                    atlas-kafka:9092
    networks:
      - csrv-net
    expose:
      - '7576'
    container_name:                         atlas-csrv-0-2
  zookeeper:
    image:                                  wurstmeister/zookeeper:3.4.6
    ports:
     - "2181:2181"
    networks:
      - kafka-net
    container_name:                         atlas-zookeeper
  kafka:
    image:                                  wurstmeister/kafka:2.13-2.6.0
    expose:
     - "9092"
    networks:
      - cos-net
      - pos-net
      - csrv-net
      - wrg-net
      - aos-net
      - mrg-net
      - morg-net
      - drg-net
      - ncs-net
      - cdc-net
      - kafka-net
    environment:
      KAFKA_ADVERTISED_LISTENERS:           INSIDE://atlas-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_LISTENERS:                      INSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME:     INSIDE
      KAFKA_ZOOKEEPER_CONNECT:              zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE:      'true'
    container_name:                         atlas-kafka
networks:
  wrg-net:
    name:                                   wrg-net
  lsrv-net:
    name:                                   lsrv-net
  aos-net:
    name:                                   aos-net
  cos-net:
    name:                                   cos-net
  iis-net:
    name:                                   iis-net
  mis-net:
    name:                                   mis-net
  pos-net:
    name:                                   pos-net
  mrg-net:
    name:                                   mrg-net
  morg-net:
    name:                                   morg-net
  dis-net:
    name:                                   dis-net
  drg-net:
    name:                                   drg-net
  tds-net:
    name:                                   tds-net
  eso-net:
    name:                                   eso-net
  sis-net:
    name:                                   sis-net
  ncs-net:
    name:                                   ncs-net
  cdc-net:
    name:                                   cdc-net
  csrv-net:
    name:                                   csrv-net
  kafka-net:
    name:                                   kafka-net
