CREATE DATABASE IF NOT EXISTS `atlas-aos`;
CREATE DATABASE IF NOT EXISTS `atlas-cos`;
CREATE DATABASE IF NOT EXISTS `atlas-dis`;
CREATE DATABASE IF NOT EXISTS `atlas-eso`;
CREATE DATABASE IF NOT EXISTS `atlas-cks`;
